"""
Base strategy engine for executing trading strategies.
Provides abstract base class for implementing custom strategies.
"""
from abc import ABC, abstractmethod
from typing import Optional, Dict, Any, List
from datetime import datetime
from sqlalchemy.ext.asyncio import AsyncSession

from ...models.market_data import Tick, Candle
from ...models.trading import Position, TradeOrder, OrderSide, OrderType
from ...utils.logging import get_logger


logger = get_logger(__name__)


class Signal:
    """Trading signal generated by strategy."""

    def __init__(
        self,
        symbol: str,
        side: OrderSide,
        signal_type: str,
        strength: float,
        price: float,
        metadata: Optional[Dict[str, Any]] = None
    ):
        self.symbol = symbol
        self.side = side
        self.signal_type = signal_type  # 'entry', 'exit', 'stop_loss', 'take_profit'
        self.strength = strength  # Signal strength 0.0 to 1.0
        self.price = price
        self.metadata = metadata or {}
        self.timestamp = datetime.utcnow()


class StrategyEngine(ABC):
    """
    Abstract base class for trading strategies.
    Implement this class to create custom trading strategies.
    """

    def __init__(
        self,
        strategy_instance_id: int,
        symbols: List[str],
        parameters: Dict[str, Any]
    ):
        """
        Initialize strategy engine.

        Args:
            strategy_instance_id: Strategy instance ID
            symbols: List of symbols to trade
            parameters: Strategy parameters
        """
        self.strategy_instance_id = strategy_instance_id
        self.symbols = symbols
        self.parameters = parameters
        self.positions: Dict[str, Position] = {}
        self.indicators: Dict[str, Dict[str, float]] = {}
        self.logger = get_logger(f"{__name__}.{self.__class__.__name__}")

    @abstractmethod
    async def on_tick(self, tick: Tick, db: AsyncSession) -> Optional[Signal]:
        """
        Process incoming tick data.

        Args:
            tick: Market tick data
            db: Database session

        Returns:
            Trading signal if generated, None otherwise
        """
        pass

    @abstractmethod
    async def on_candle(self, candle: Candle, db: AsyncSession) -> Optional[Signal]:
        """
        Process incoming candle data.

        Args:
            candle: OHLCV candle data
            db: Database session

        Returns:
            Trading signal if generated, None otherwise
        """
        pass

    @abstractmethod
    async def calculate_indicators(
        self,
        symbol: str,
        candles: List[Candle]
    ) -> Dict[str, float]:
        """
        Calculate technical indicators for a symbol.

        Args:
            symbol: Trading symbol
            candles: Historical candle data

        Returns:
            Dictionary of indicator values
        """
        pass

    async def should_enter_position(
        self,
        symbol: str,
        tick: Tick
    ) -> Optional[Signal]:
        """
        Determine if strategy should enter a position.

        Args:
            symbol: Trading symbol
            tick: Current tick data

        Returns:
            Entry signal if conditions met, None otherwise
        """
        # To be implemented by specific strategy
        return None

    async def should_exit_position(
        self,
        position: Position,
        tick: Tick
    ) -> Optional[Signal]:
        """
        Determine if strategy should exit a position.

        Args:
            position: Current position
            tick: Current tick data

        Returns:
            Exit signal if conditions met, None otherwise
        """
        # To be implemented by specific strategy
        return None

    def calculate_position_size(
        self,
        symbol: str,
        price: float,
        signal_strength: float
    ) -> int:
        """
        Calculate position size based on risk parameters.

        Args:
            symbol: Trading symbol
            price: Entry price
            signal_strength: Signal strength (0.0 to 1.0)

        Returns:
            Position size in units
        """
        max_position_value = self.parameters.get('max_position_size', 10000)
        position_value = max_position_value * signal_strength
        quantity = int(position_value / price)
        return max(1, quantity)

    def update_position(
        self,
        symbol: str,
        position: Position
    ) -> None:
        """
        Update internal position tracking.

        Args:
            symbol: Trading symbol
            position: Position object
        """
        self.positions[symbol] = position

    def remove_position(self, symbol: str) -> None:
        """
        Remove position from tracking.

        Args:
            symbol: Trading symbol
        """
        if symbol in self.positions:
            del self.positions[symbol]

    def get_position(self, symbol: str) -> Optional[Position]:
        """
        Get current position for symbol.

        Args:
            symbol: Trading symbol

        Returns:
            Position if exists, None otherwise
        """
        return self.positions.get(symbol)

    def has_position(self, symbol: str) -> bool:
        """
        Check if strategy has open position for symbol.

        Args:
            symbol: Trading symbol

        Returns:
            True if position exists
        """
        return symbol in self.positions


class MomentumStrategy(StrategyEngine):
    """Example momentum-based trading strategy."""

    async def on_tick(self, tick: Tick, db: AsyncSession) -> Optional[Signal]:
        """Process tick for momentum signals."""
        # Example implementation
        if tick.symbol not in self.symbols:
            return None

        # Check if we have a position
        if self.has_position(tick.symbol):
            position = self.get_position(tick.symbol)
            return await self.should_exit_position(position, tick)
        else:
            return await self.should_enter_position(tick.symbol, tick)

    async def on_candle(self, candle: Candle, db: AsyncSession) -> Optional[Signal]:
        """Process candle for momentum signals."""
        # Update indicators when new candle arrives
        # This is a simplified example
        return None

    async def calculate_indicators(
        self,
        symbol: str,
        candles: List[Candle]
    ) -> Dict[str, float]:
        """Calculate momentum indicators."""
        # Example: Calculate simple moving averages
        if len(candles) < 20:
            return {}

        closes = [c.close for c in candles]
        sma_10 = sum(closes[-10:]) / 10
        sma_20 = sum(closes[-20:]) / 20

        return {
            'sma_10': sma_10,
            'sma_20': sma_20,
            'momentum': sma_10 - sma_20
        }
